version: '3'
services:

  mabinogi_db:
    image: mysql:5.7-debian
    platform: linux/amd64
    ports:
      - "51122:3306"
    expose:
      - "51122" # 65536
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mabinogi
    volumes:
      - "./sqls/:/docker-entrypoint-initdb.d/"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
